hethongquanlyluutrufiles/Areas/Admin/Controllers/AdminPermissViewFileAllController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using hethongquanlyluutrufiles.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PagedList.Core;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace hethongquanlyluutrufiles.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminPermissViewFileAllController : Controller
    {
        private readonly hethongquanlyluutrufileContext _context;
        public INotyfService _notyfService { get; }

        public AdminPermissViewFileAllController(hethongquanlyluutrufileContext context, INotyfService notyfService)
        {
            _context = context;
            _notyfService = notyfService;
        }
        public IActionResult SelectFile(int? page)
        {
            var userID = HttpContext.Session.GetString("UserId");


            var pageNumber = page == null || page <= 0 ? 1 : page.Value;
            var pageSize = 10;
            var lsFiles = _context.Files
                .AsNoTracking()
                .Include(x => x.TypeFile)
                .Where(x => x.UserId == Convert.ToInt32(userID) && x.IsActive == true)
                .OrderBy(x => x.DateUploaded);
            PagedList<File> models = new PagedList<File>(lsFiles, pageNumber, pageSize);
            ViewBag.CurrentPage = pageNumber;
            return View(models);
        }
        public async Task<IActionResult> PermissViewFile(int? fileid)
        {

            if (fileid == null)
            {
                return NotFound();
            }

            var file = await _context.Files
                .Include(f => f.TypeFile)
                .FirstOrDefaultAsync(m => m.FileId == fileid);

            if (file == null)
            {
                return NotFound();
            }

            ViewBag.file = file;

            // người gửi
            var userID = HttpContext.Session.GetString("UserId");
            var usersend = await _context.Users
                .Include(m => m.Role)
                .Include(m => m.Department)
                .FirstOrDefaultAsync(m => m.UserId == Convert.ToInt32(userID));

            if (usersend == null)
            {
                return NotFound();
            }
            ViewBag.usersend = usersend;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> PermissViewFile(int fileid, SharedFile s)
        {
            if (ModelState.IsValid)
            {
                var userID = HttpContext.Session.GetString("UserId");
               

                List<User> lsuser = new List<User>();
                lsuser = _context.Users.Where(x => x.UserId != Convert.ToInt32(userID)).ToList();

                foreach (var lu in lsuser)
                {
                    SharedFile sf = new SharedFile();
                    sf.FileId = fileid;
                    sf.SharedWithUserId = lu.UserId;
                    sf.Message = s.Message;
                    sf.DateShared = DateTime.Now;
                    sf.Notify = true;
                    _context.SharedFiles.Add(sf);
                }

                await _context.SaveChangesAsync();
                _notyfService.Success("Chia sẻ file thành công");
                return RedirectToAction("TrangChuAdmin", "Home", new { area = "Admin" });
            }
            return View(fileid);
        }
    }
}

hethongquanlyluutrufiles/Areas/Admin/Views/AdminPermissViewFileAll/PermissViewFile.cshtml
@model hethongquanlyluutrufiles.Models.SharedFile
@{
    ViewData["Title"] = "Cấp quyền xem file";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
@{
    var file = ViewBag.file as File;
    var usersend = ViewBag.usersend as User;
}
<div class="card">
    <div class="card-body">
        <div id="invoice" class="p-h-30">
            <div class="m-t-15 lh-2">
                <div class="inline-block">
                    <img class="img-fluid" src="assets/images/logo/logo.png" alt="">
                    <address class="p-l-10">
                        <span class="font-weight-semibold text-dark">Công ty kinh doanh và đầu tư</span><br>
                        <span> 241 - Hoàng Quốc Việt - Bắc Từ Liêm - TP Hà Nội</span><br>
                        <abbr class="text-dark">Phone:</abbr>
                        <span>(123) 456-7890</span>
                    </address>
                </div>
                <div class="float-right">
                    <h2>CONFIRM</h2>
                </div>
            </div>
            <div class="form-row">
                <div class="col-sm-6">
                <h3 class="p-l-10 m-t-10">Người gửi:</h3>
                <address class="p-l-10">
                    <span class="font-weight-semibold text-dark">@usersend.Username</span><br>
                    <abbr class="text-dark" >Chức vụ:</abbr>
                        <span>Tổng giám đốc</span><br>
                    <abbr class="text-dark">Phone:</abbr>
                        <span>@usersend.Phone</span>
                </address>
            </div>
                <div class="col-sm-6">
                    <h3 class="p-l-10 m-t-10">Người nhận:</h3>
                    <address class="p-l-10">
                        <abbr class="text-dark">Đối tượng:</abbr>
                        <span>Toàn bộ người dùng trong hệ thống</span><br>

                    </address>
                </div>
            </div>
            <div class="m-t-20">
                <div class="table-responsive">
                    <table class="product-info-table m-t-20">
                        <tbody>
                            <tr>
                                <td>ID:</td>
                                <td>@file.FileId</td>
                            </tr>
                            <tr>
                                <td>Tên file:</td>
                                <td>@file.FileName</td>
                            </tr>
                            <tr>
                                <td>Loại file:</td>
                                <td>@file.TypeFile.TypeFileName</td>
                            </tr>
                            <tr>
                                <td>Xác nhận quyền xem file:</td>
                                <td>
                                    <form asp-action="PermissViewFile">
                                        <input type="hidden" name="fileid" value="@file.FileId" />
                                        <div class="form-group">
                                            <label class="control-label">Message:</label>
                                            <textarea asp-for="Message" class="form-control" aria-label="With textarea"></textarea>
                                            <span asp-validation-for="Message" class="text-danger"></span>
                                        </div>
                                        <input type="submit" class="btn btn-primary" value="Chia sẻ" />
                                        <button class="btn btn-primary btn-tone m-r-5" asp-area="Admin" asp-controller="AdminPermissViewFileAll" asp-action="SelectFile">Trở lại</button>
                                    </form>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

</div>

hethongquanlyluutrufiles/Areas/Admin/Views/AdminPermissViewFileAll/SelectFile.cshtml
@using PagedList.Core.Mvc
@model PagedList.Core.IPagedList<hethongquanlyluutrufiles.Models.File>

@{
    int CurrentPage = ViewBag.CurrentPage;
    ViewData["Title"] = "Chọn file chia sẻ" + CurrentPage;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
    <h2 class="header-title">Chọn file chia sẻ</h2>
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="TrangChuAdmin" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
        </nav>
    </div>
</div>

<div class="card">
    <div class="card-body">
        <div class="col m-b-30">
            <div class="col-lg-8">
                <div class="col-md-6">
                    <div class="input-affix m-v-10">
                        <i class="prefix-icon anticon anticon-search opacity-04"></i>
                        <input id="keyword" name="keyword" type="text" class="form-control" placeholder="Tìm kiếm file">
                    </div>
                </div>
            </div>
            <div >
                <table class="table table-hover">
                    <thead>
                        <tr role="row">
                            <th>ID</th>
                            <th>Tên file</th>
                            <th>Loại file</th>
                            <th>Thời gian tạo</th>
                            <th>
                            </th>
                        </tr>
                    </thead>
                    <tbody id="records_table">
                        @if (Model != null)
                        {
                            foreach (var item in Model)
                            {
                                <tr role="row" class="odd">
                                    <td> @item.FileId</td>
                                    <td>@item.FileName</td>
                                    <td>@item.TypeFile.TypeFileName</td>
                                    <td>@item.DateUploaded </td>
                                    <td class="text-right">
                                        <a class="btn btn-primary btn-tone m-r-5" asp-area="Admin" asp-controller="AdminPermissViewFileAll" asp-action="PermissViewFile" asp-route-fileid="@item.FileId">Chọn</a>

                                    </td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
        <div aria-label="Page navigation example" style="float: right">
            <ul class="pagination">
                <pager class="pager-container" list="@Model" asp-area="Admin" asp-controller="AdminPermissViewFileAll" asp-action="SelectFile" />
            </ul>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        $("#keyword").keyup(function () {
            var strkeyword = $('#keyword').val();
            $.ajax({
                url: '/Admin/Search/FindFilesShared_All',
                datatype: "json",
                type: "POST",
                data: { keyword: strkeyword },
                async: true,
                success: function (results) {
                    $("#records_table").html("");
                    $("#records_table").html(results);
                },
                error: function (xhr) {
                    alert('error');
                }
            });
        });
    </script>
}