hethongquanlyluutrufiles/Controllers/FilesPersonalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using hethongquanlyluutrufiles.Models;
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Http;
using PagedList.Core;
using System.IO;
using File = hethongquanlyluutrufiles.Models.File;

namespace hethongquanlyluutrufiles.Controllers
{
    public class FilesPersonalController : Controller
    {
        private readonly hethongquanlyluutrufileContext _context;
        public INotyfService _notyfService { get; }
        public FilesPersonalController(hethongquanlyluutrufileContext context, INotyfService notyfService)
        {
            _context = context;
            _notyfService = notyfService;
        }

        public IActionResult Index(int page = 1, int typeFileID = 0)
        {
            var pageNumber = page;
            var pageSize = 10;

            var userID = HttpContext.Session.GetString("UserId");
            List<File> listfile = new List<File>();

            if (typeFileID != 0)
            {
                listfile = _context.Files
                    .AsNoTracking()
                    .Where(x => x.UserId == Convert.ToInt32(userID) && x.TypeFileId == typeFileID && x.IsActive == true)
                    .Include(x => x.TypeFile)
                    .OrderByDescending(x => x.FileId).ToList();
            }
            else
            {
                listfile = _context.Files
                    .AsNoTracking()
                    .Where(x => x.UserId == Convert.ToInt32(userID) && x.IsActive == true)
                    .Include(x => x.TypeFile)
                    .OrderByDescending(x => x.FileId).ToList();
            }


            PagedList<File> models = new PagedList<File>(listfile.AsQueryable(), pageNumber, pageSize);
            ViewBag.CurrentTypeFileID = typeFileID;
            ViewBag.CurrentPage = pageNumber;
            ViewData["typefile"] = new SelectList(_context.TypeFiles, "TypeFileId", "TypeFileName");

            return View(models);
        }

        public IActionResult Filtter(int typeFileID = 0)
        {
            var url = $"/FilesPersonal/Index?typeFileID={typeFileID}";
            if (typeFileID == 0)
            {
               url = $"/FilesPersonal/Index";
            }
            return Json(new { status = "success", redirectUrl = url });
        }
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var file = await _context.Files
                .Include(f => f.TypeFile)
                .Include(f => f.User)
                .FirstOrDefaultAsync(m => m.FileId == id);
            if (file == null)
            {
                return NotFound();
            }

            return View(file);
        }

        public IActionResult Create()
        {
            ViewData["typefile"] = new SelectList(_context.TypeFiles, "TypeFileId", "TypeFileName");

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FileId,UserId,FileName,FilePath,FileSize,DateUploaded,TypeFileId,IsActive")] File f, [FromForm] IFormFile myfile)
        {
            if (ModelState.IsValid)
            {
                var filesize = myfile.Length;
                if (myfile == null || filesize == 0)
                {
                    ModelState.AddModelError("", "Vui lòng chọn một file để tải lên.");
                    return View();
                }
                // get the file name and extension
                string fileName = Path.GetFileName(myfile.FileName);
                string fileExtension = Path.GetExtension(fileName);

                // create a unique file name using a GUID
                string uniqueFileName = Guid.NewGuid().ToString().Substring(0, 10) + fileExtension;
                f.FilePath = uniqueFileName;

                // get the path to the uploads directory
                string uploadsPath = Path.Combine(Directory.GetCurrentDirectory(), "FileUploaded");

                // create the uploads directory if it doesn't exist
                if (!Directory.Exists(uploadsPath))
                {
                    Directory.CreateDirectory(uploadsPath);
                }

                // create the full path to the uploaded file
                string filePath = Path.Combine(uploadsPath, uniqueFileName);


                // copy the file to the uploads directory
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    myfile.CopyTo(fileStream);
                }
                var userID = HttpContext.Session.GetString("UserId");

                f.FileSize = (filesize / 1024);
                f.DateUploaded = DateTime.Now;
                f.UserId = Convert.ToInt32(userID);

                _context.Add(f);
                await _context.SaveChangesAsync();
                _notyfService.Success("Tạo file mới thành công");
                return RedirectToAction(nameof(Index));
            }
            ViewData["typefile"] = new SelectList(_context.TypeFiles, "TypeFileId", "TypeFileName");
            return View(f);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var file = await _context.Files.FindAsync(id);
            if (file == null)
            {
                return NotFound();
            }
            ViewData["typefile"] = new SelectList(_context.TypeFiles, "TypeFileId", "TypeFileName");
            return View(file);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int Fileid, [Bind("FileId,UserId,FileName,FilePath,FileSize,DateUploaded,TypeFileId,IsActive")] File file)
        {
            if (Fileid != file.FileId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(file);
                    await _context.SaveChangesAsync();
                    _notyfService.Success("Chỉnh sửa file thành công");

                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FileExists(file.FileId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["typefile"] = new SelectList(_context.TypeFiles, "TypeFileId", "TypeFileName");
            return View(file);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var file = await _context.Files
                .Include(f => f.TypeFile)
                .Include(f => f.User)
                .FirstOrDefaultAsync(m => m.FileId == id);
            if (file == null)
            {
                return NotFound();
            }

            return View(file);
        }

        // POST: Admin/AdminFiles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            File f = await _context.Files.FindAsync(id);
            if (f == null)
            {
                return NotFound();
            }
            f.IsActive = false;
            _context.Update(f);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FileExists(int id)
        {
            return _context.Files.Any(e => e.FileId == id);
        }
    }
}

hethongquanlyluutrufiles/Controllers/FilesReceivedController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using hethongquanlyluutrufiles.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PagedList.Core;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using File = hethongquanlyluutrufiles.Models.File;

namespace hethongquanlyluutrufiles.Controllers
{
    public class FilesReceivedController : Controller
    {
        private readonly hethongquanlyluutrufileContext _context;
        public INotyfService _notyfService { get; }

        public FilesReceivedController(hethongquanlyluutrufileContext context, INotyfService notyfService)
        {
            _context = context;
            _notyfService = notyfService;
        }
        
        public IActionResult Index(int? page)
        {
            var userID = HttpContext.Session.GetString("UserId");
            var pageNumber = page == null || page <= 0 ? 1 : page.Value;
            var pageSize = 10;

            var sharefile = _context.SharedFiles
                            .AsNoTracking()
                            .Include(x => x.File)
                            .Include(x => x.File.User)
                            .Where(x => x.SharedWithUserId == Convert.ToInt32(userID) && x.File.IsActive == true)
                            .OrderByDescending(x => x.DateShared);
            PagedList<SharedFile> models = new PagedList<SharedFile>(sharefile, pageNumber, pageSize);

            ViewBag.CurrentPage = pageNumber;
            return View(models);
        }
      
        public ActionResult Details(int? id, int? sharefileid)
        {
            if (id == null)
            {
                return NotFound();
            }
            if (sharefileid == null)
            {
                return NotFound();
            }

            var file = _context.Files
                .Include(f => f.TypeFile)
                .Include(f => f.User)
                .FirstOrDefault(m => m.FileId == id);


            if (file == null)
            {
                return NotFound();
            }

            var sharefile = _context.SharedFiles.AsNoTracking().FirstOrDefault(x => x.SharedFileId == sharefileid);
            if (sharefile.Notify == true)
            {
                sharefile.Notify = false;
                _context.Update(sharefile);
                _context.SaveChangesAsync();
            }
            
            return View(file);
        }


        public async Task<IActionResult> Download(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var file = await _context.Files
                .Include(f => f.TypeFile)
                .Include(f => f.User)
                .FirstOrDefaultAsync(m => m.FileId == id);
            if (file == null)
            {
                return NotFound();
            }

            return View(file);
        }
        [HttpPost, ActionName("Download")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DownloadConfirmed(int id)
        {
            var file = await _context.Files.FindAsync(id);
            string uploadsPath = Path.Combine(Directory.GetCurrentDirectory(), "FileUploaded");
            string filePath = Path.Combine(uploadsPath, file.FilePath);
            byte[] fileBytes = System.IO.File.ReadAllBytes(filePath);

            return File(
                fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, file.FilePath);
        }
    }
}

hethongquanlyluutrufiles/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using hethongquanlyluutrufiles.Models;
using Microsoft.AspNetCore.Http;
using AspNetCoreHero.ToastNotification.Abstractions;
using hethongquanlyluutrufiles.ModelViews;
using Microsoft.AspNetCore.Authorization;

namespace hethongquanlyluutrufiles.Controllers
{
    public class UsersController : Controller
    {
        private readonly hethongquanlyluutrufileContext _context;

        public INotyfService _notyfService { get; }

        public UsersController(hethongquanlyluutrufileContext context, INotyfService notyfService)
        {
            _context = context;
            _notyfService = notyfService;
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details()
        {
            var userID = HttpContext.Session.GetString("UserId");
            var user = await _context.Users
                .Include(u => u.Department)
                .Include(u => u.Role)
                .FirstOrDefaultAsync(u => u.UserId == Convert.ToInt32(userID));

            return View(user);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            ViewData["department"] = new SelectList(_context.Departments, "DepartmentId", "DepartmentName");
            ViewData["typerole"] = new SelectList(_context.Roles, "RoleId", "TypeRole");
            return View();
        }

        // POST: Users/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(UserModel userModel)
        {
            if (ModelState.IsValid)
            {
                var userID = HttpContext.Session.GetString("UserId");
                var user = _context.Users.AsNoTracking().SingleOrDefault(x => x.UserId == Convert.ToInt32(userID));
                if (user == null)
                {
                    return NotFound();
                }

                user.Birthday = userModel.Birthday;
                user.Sex = userModel.Sex;
                user.Address = userModel.Address;
                user.Cmnd = userModel.Cmnd;
                user.RoleId = userModel.RoleId;
                user.DepartmentId = userModel.DepartmentId;
                user.Typework = userModel.Typework;
                user.Company = userModel.Company;
                user.Workplace = userModel.Workplace;

                _context.Update(user);
                await _context.SaveChangesAsync();
                _notyfService.Success("Tạo thông tin người dùng thành công");
                return RedirectToAction("TrangChuUser", "Home");
            }
            ViewData["department"] = new SelectList(_context.Departments, "DepartmentId", "DepartmentName");
            ViewData["typerole"] = new SelectList(_context.Roles, "RoleId", "TypeRole");
            return View(userModel);
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit()
        {
            var userID = HttpContext.Session.GetString("UserId");

            var user = await _context.Users.FindAsync(Convert.ToInt32(userID));
            if (user == null)
            {
                return NotFound();
            }
            ViewData["department"] = new SelectList(_context.Departments, "DepartmentId", "DepartmentName");
            ViewData["typerole"] = new SelectList(_context.Roles, "RoleId", "TypeRole");
            return View(user);
        }

        // POST: Users/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int UserId, [Bind("UserId,Username,Email,Password,Salt,IsAdminOrUser,Birthday,Sex,Address,Phone,Cmnd,RoleId,DepartmentId,Typework,Company,Workplace,IsActive,AbleShared")] User user)
        {
            if (UserId != user.UserId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    _notyfService.Success("Thay đổi thông tin người dùng thành công");
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.UserId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("TrangChuUser", "Home");
            }
            ViewData["department"] = new SelectList(_context.Departments, "DepartmentId", "DepartmentName");
            ViewData["typerole"] = new SelectList(_context.Roles, "RoleId", "TypeRole");
            return View();
        }

        private bool UserExists(int id)
        {
            return _context.Users.Any(e => e.UserId == id);
        }
    }
}

hethongquanlyluutrufiles/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
@{
    var username = HttpContextAccessor.HttpContext.Session.GetString("Username");
}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Enlink - Admin Dashboard Template</title>

    <!-- Favicon -->
    <link rel="shortcut icon" href="~/AdminAsessts/images/logo/favicon.png">

    <!-- page css -->
    <link href="~/AdminAsessts/vendors/bootstrap-datepicker/bootstrap-datepicker.min.css" rel="stylesheet">

    <!-- Core css -->
    <link href="~/AdminAsessts/css/app.min.css" rel="stylesheet">

</head>

<body>
    <div class="app">
        <div class="layout">
            <!-- Header START -->
            <div class="header">
                <div class="logo logo-dark">
                    <a href="#">
                        <img src="~/AdminAsessts/images/logo/logo.png" alt="Logo">
                        <img class="logo-fold" src="~/AdminAsessts/images/logo/logo-fold.png" alt="Logo">
                    </a>
                </div>
                <div class="logo logo-white">
                    <a href="#">
                        <img src="~/AdminAsessts/images/logo/logo-white.png" alt="Logo">
                        <img class="logo-fold" src="~/AdminAsessts/images/logo/logo-fold-white.png" alt="Logo">
                    </a>
                </div>
                <div class="nav-wrap">
                    <ul class="nav-left">
                        <li class="desktop-toggle">
                            <a href="javascript:void(0);">

                                <i class="anticon"></i>
                            </a>
                        </li>
                        <li class="mobile-toggle">
                            <a href="javascript:void(0);">
                                <i class="anticon"></i>
                            </a>
                        </li>
                    </ul>
                    <ul class="nav-right">                       
                        <li class="dropdown dropdown-animated scale-left">
                            <div class="pointer" data-toggle="dropdown">
                                <div class="avatar avatar-image  m-h-10 m-r-15">
                                    <img src="~/AdminAsessts/images/avatars/thumb-3.jpg" alt="">
                                </div>
                            </div>
                            <div class="p-b-15 p-t-20 dropdown-menu pop-profile">
                                <div class="p-h-20 p-b-15 m-b-10 border-bottom">
                                    <div class="d-flex m-r-50">
                                        <div class="avatar avatar-lg avatar-image">
                                            <img src="~/AdminAsessts/images/avatars/thumb-3.jpg" alt="">
                                        </div>
                                        <div class="m-l-10">
                                            <a asp-area="" asp-controller="Users" asp-action="Details" class="m-b-0 text-dark font-weight-semibold">@username</a>
                                            <a class="m-b-0 opacity-07">Người dùng</a>
                                        </div>
                                    </div>
                                </div>
                                <a asp-area="" asp-controller="Users" asp-action="Edit" class="dropdown-item d-block p-h-15 p-v-10">
                                    <div class="d-flex align-items-center justify-content-between">
                                        <div>
                                            <i class="anticon opacity-04 font-size-16 anticon-user"></i>
                                            <span class="m-l-10">Thay đổi thông tin cá nhân</span>
                                        </div>
                                        <i class="anticon font-size-10 anticon-right"></i>
                                    </div>
                                </a>
                                <a asp-area="" asp-controller="Accounts" asp-action="ChangePassword" class="dropdown-item d-block p-h-15 p-v-10">
                                    <div class="d-flex align-items-center justify-content-between">
                                        <div>
                                            <i class="anticon opacity-04 font-size-16 anticon-lock"></i>
                                            <span class="m-l-10">Cài đặt tài khoản</span>
                                        </div>
                                        <i class="anticon font-size-10 anticon-right"></i>
                                    </div>
                                </a>
                                <a asp-controller="Accounts" asp-action="Logout" class="dropdown-item d-block p-h-15 p-v-10">
                                    <div class="d-flex align-items-center justify-content-between">
                                        <div>
                                            <i class="anticon opacity-04 font-size-16 anticon-logout"></i>
                                            <span class="m-l-10">Đăng xuất</span>
                                        </div>
                                        <i class="anticon font-size-10 anticon-right"></i>
                                    </div>
                                </a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
            <!-- Header END -->
            @await Html.PartialAsync("_UserSideNavPartialView.cshtml")
            <!-- Side Nav END -->
            <!-- Page Container START -->
            <div class="page-container">

                <!-- Content Wrapper START -->
                <div class="main-content">
                    @RenderBody()
                </div>
                <!-- Content Wrapper END -->
                <!-- Footer START -->
                <footer class="footer">
                    <div class="footer-content">
                        <p class="m-b-0">Copyright © 2019 Theme_Nate. All rights reserved.</p>
                        <span>
                            <a href="" class="text-gray m-r-15">Term &amp; Conditions</a>
                            <a href="" class="text-gray">Privacy &amp; Policy</a>
                        </span>
                    </div>
                </footer>
                <!-- Footer END -->

            </div>
            <!-- Page Container END -->
        </div>
    </div>


    <!-- Core Vendors JS -->
    <script src="~/AdminAsessts/js/vendors.min.js"></script>

    <!-- page js -->
    <script src="~/AdminAsessts/vendors/chartjs/Chart.min.js"></script>
    <script src="~/AdminAsessts/js/pages/dashboard-e-commerce.js"></script>

    <!-- Core JS -->
    <script src="~/AdminAsessts/js/app.min.js"></script>
    @await Component.InvokeAsync("Notyf")
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

hethongquanlyluutrufiles/Views/Shared/_UserSideNavPartialView.cshtml
<!-- Side Nav START -->
<div class="side-nav">
    <div class="side-nav-inner">
        <ul class="side-nav-menu scrollable">
            <li class="nav-item">
                <a class="dropdown-toggle" asp-area="" asp-controller="Home" asp-action="TrangChuUser">
                    <span class="icon-holder">
                        <i class="anticon anticon-dashboard"></i>
                    </span>
                    <span class="title">Trang chủ</span>
                    <span class="arrow">
                        <i class="arrow-icon"></i>
                    </span>
                </a>
            </li>
            <li class="nav-item dropdown">
                <a class="dropdown-toggle" href="javascript:void(0);">
                    <span class="icon-holder">
                        <i class="anticon anticon-appstore"></i>
                    </span>
                    <span class="title">Quản lý file</span>
                    <span class="arrow">
                        <i class="arrow-icon"></i>
                    </span>
                </a>
                <ul class="dropdown-menu">
                    <li>
                        <a asp-area="" asp-controller="FilesReceived" asp-action="Index">Danh sách file hệ thống</a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="FilesPersonal" asp-action="Index">Danh sách file cá nhân</a>
                    </li>
                </ul>
            </li>
            <li class="nav-item dropdown">
                <a class="dropdown-toggle" href="javascript:void(0);">
                    <span class="icon-holder">
                        <i class="anticon anticon-hdd"></i>
                    </span>
                    <span class="title">Cấp quyền truy cập file</span>
                    <span class="arrow">
                        <i class="arrow-icon"></i>
                    </span>
                </a>
                <ul class="dropdown-menu">
                    <li>
                        
                        <a asp-area="" asp-controller="Home" asp-action="AuthorShareFile" asp-route-index="1">Toàn bộ người dùng</a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Home" asp-action="AuthorShareFile" asp-route-index="2">Mỗi phòng ban</a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Home" asp-action="AuthorShareFile" asp-route-index="3">Mỗi người dùng</a>
                    </li>
                </ul>
            </li>
            <li class="nav-item dropdown">
                <a class="dropdown-toggle" href="javascript:void(0);">
                    <span class="icon-holder">
                        <i class="anticon anticon-lock"></i>
                    </span>
                    <span class="title">Tiện ích</span>
                    <span class="arrow">
                        <i class="arrow-icon"></i>
                    </span>
                </a>
                <ul class="dropdown-menu">
                    <li>
                        <a asp-area="" asp-controller="Home" asp-action="LogShareFile">Nhật ký chia sẻ file</a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Home" asp-action="HistoryDeleteFile">Lịch sử xóa file</a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</div>