hethongquanlyluutrufiles/Areas/Admin/Controllers/AdminFilesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using hethongquanlyluutrufiles.Models;
using AspNetCoreHero.ToastNotification.Abstractions;
using PagedList.Core;
using Microsoft.AspNetCore.Http;
using System.IO;
using File = hethongquanlyluutrufiles.Models.File;

namespace hethongquanlyluutrufiles.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminFilesController : Controller
    {
        private readonly hethongquanlyluutrufileContext _context;

        public INotyfService _notyfService { get; }

        public AdminFilesController(hethongquanlyluutrufileContext context, INotyfService notyfService)
        {
            _context = context;
            _notyfService = notyfService;
        }


        public IActionResult Index(int page = 1, int typeFileID = 0)
        {
            var pageNumber = page;
            var pageSize = 10;

            var userID = HttpContext.Session.GetString("UserId");
            List<File> listfile = new List<File>();

            if (typeFileID != 0)
            {
                listfile = _context.Files
                    .AsNoTracking()
                    .Where(x => x.UserId == Convert.ToInt32(userID) && x.TypeFileId == typeFileID && x.IsActive == true)
                    .Include(x => x.TypeFile)
                    .OrderByDescending(x => x.DateUploaded).ToList();
            }
            else
            {
                listfile = _context.Files
                    .AsNoTracking()
                    .Where(x => x.UserId == Convert.ToInt32(userID) && x.IsActive == true)
                    .Include(x => x.TypeFile)
                    .OrderByDescending(x => x.DateUploaded).ToList();
            }


            PagedList<File> models = new PagedList<File>(listfile.AsQueryable(), pageNumber, pageSize);
            ViewBag.CurrentTypeFileID = typeFileID;
            ViewBag.CurrentPage = pageNumber;
            ViewData["typefile"] = new SelectList(_context.TypeFiles, "TypeFileId", "TypeFileName");

            return View(models);
        }

        public IActionResult Filtter(int typeFileID = 0)
        {
            var url = $"/Admin/AdminFiles?typeFileID={typeFileID}";
            if (typeFileID == 0)
            {
                url = $"/Admin/AdminFiles";
            }
            return Json(new { status = "success", redirectUrl = url });
        }
        // GET: Admin/AdminFiles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var file = await _context.Files
                .Include(f => f.TypeFile)
                .Include(f => f.User)
                .FirstOrDefaultAsync(m => m.FileId == id);
            if (file == null)
            {
                return NotFound();
            }

            return View(file);
        }

        // GET: Admin/AdminFiles/Create
        public IActionResult Create()
        {
            ViewData["typefile"] = new SelectList(_context.TypeFiles, "TypeFileId", "TypeFileName");

            return View();
        }

        // POST: Admin/AdminFiles/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FileId,UserId,FileName,FilePath,FileSize,DateUploaded,TypeFileId,IsActive")] File f, [FromForm] IFormFile myfile)
        {
            if (ModelState.IsValid)
            {
                var filesize = myfile.Length;
                if (myfile == null || filesize == 0)
                {
                    ModelState.AddModelError("", "Vui lòng chọn một file để tải lên.");
                    return View();
                }
                // get the file name and extension
                string fileName = Path.GetFileName(myfile.FileName);
                string fileExtension = Path.GetExtension(fileName);

                // create a unique file name using a GUID
                string uniqueFileName = Guid.NewGuid().ToString().Substring(0, 10) + fileExtension;
                f.FilePath = uniqueFileName;

                // get the path to the uploads directory
                string uploadsPath = Path.Combine(Directory.GetCurrentDirectory(), "FileUploaded");

                // create the uploads directory if it doesn't exist
                if (!Directory.Exists(uploadsPath))
                {
                    Directory.CreateDirectory(uploadsPath);
                }

                // create the full path to the uploaded file
                string filePath = Path.Combine(uploadsPath, uniqueFileName);


                // copy the file to the uploads directory
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    myfile.CopyTo(fileStream);
                }
                var userID = HttpContext.Session.GetString("UserId");

                f.FileSize = (filesize/1024);
                f.DateUploaded = DateTime.Now;
                f.UserId = Convert.ToInt32(userID);

                _context.Add(f);
                await _context.SaveChangesAsync();
                _notyfService.Success("Tạo file mới thành công");
                return RedirectToAction(nameof(Index));
            }
            ViewData["typefile"] = new SelectList(_context.TypeFiles, "TypeFileId", "TypeFileName");
            return View(f);
        }

        // GET: Admin/AdminFiles/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
       
            var file = await _context.Files.FindAsync(id);
            if (file == null)
            {
                return NotFound();
            }
            ViewData["typefile"] = new SelectList(_context.TypeFiles, "TypeFileId", "TypeFileName");
            return View(file);
        }

        // POST: Admin/AdminFiles/Edit/5
  
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int Fileid, [Bind("FileId,UserId,FileName,FilePath,FileSize,DateUploaded,TypeFileId,IsActive")] File file)
        {
            if (Fileid != file.FileId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(file);
                    await _context.SaveChangesAsync();
                    _notyfService.Success("Chỉnh sửa file thành công");

                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FileExists(file.FileId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["typefile"] = new SelectList(_context.TypeFiles, "TypeFileId", "TypeFileName");
            return View(file);
        }

        // GET: Admin/AdminFiles/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var file = await _context.Files
                .Include(f => f.TypeFile)
                .Include(f => f.User)
                .FirstOrDefaultAsync(m => m.FileId == id);
            if (file == null)
            {
                return NotFound();
            }

            return View(file);
        }

        // POST: Admin/AdminFiles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            File f = await _context.Files.FindAsync(id);
            if(f == null)
            {
                return NotFound();
            }
            f.IsActive = false;
            _context.Update(f);
            await _context.SaveChangesAsync();
            _notyfService.Success("Xóa file thành công");
            return RedirectToAction(nameof(Index));
        }

        private bool FileExists(int id)
        {
            return _context.Files.Any(e => e.FileId == id);
        }
    }
}

hethongquanlyluutrufiles/Areas/Admin/Controllers/AdminUsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using hethongquanlyluutrufiles.Models;
using AspNetCoreHero.ToastNotification.Abstractions;
using PagedList.Core;
using Microsoft.AspNetCore.Http;

namespace hethongquanlyluutrufiles.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminUsersController : Controller
    {
        private readonly hethongquanlyluutrufileContext _context;

        public INotyfService _notyfService { get; }

        public AdminUsersController(hethongquanlyluutrufileContext context, INotyfService notyfService)
        {
            _context = context;
            _notyfService = notyfService;
        }

        // GET: Admin/AdminUsers
        public IActionResult Index(int page = 1, int DepID = 0)
        {
            var pageNumber = page;
            var pageSize = 10;
            var userID = HttpContext.Session.GetString("UserId");


            List<User> listuser = new List<User>();

            if (DepID != 0)
            {
                listuser = _context.Users
                    .AsNoTracking()
                    .Include(x => x.Department)
                    .Where(x => x.DepartmentId == DepID && x.UserId != Convert.ToInt32(userID))
                    .OrderByDescending(x => x.UserId).ToList();
            }
            else
            {
                listuser = _context.Users
                    .Include(x => x.Department)
                    .Where(x => x.UserId != Convert.ToInt32(userID))
                    .AsNoTracking()
                    .OrderByDescending(x => x.UserId).ToList();
            }


            PagedList<User> models = new PagedList<User>(listuser.AsQueryable(), pageNumber, pageSize);
            ViewBag.CurrentDepartment = DepID;
            ViewBag.CurrentPage = pageNumber;
            ViewData["Department"] = new SelectList(_context.Departments, "DepartmentId", "DepartmentName");

            return View(models);
        }

        public IActionResult Filtter(int DepID = 0)
        {
            var url = $"/Admin/AdminUsers?DepID={DepID}";
            if (DepID == 0)
            {
                url = $"/Admin/AdminUsers";
            }
            return Json(new { status = "success", redirectUrl = url });
        }

        [HttpPost]
        public IActionResult UpdateSwitch(int id, bool value)
        {
            var user = _context.Users.Find(id);
            user.AbleShared = value;
          
            _context.Update(user);
            _context.SaveChanges();

            // xử lý sự kiện tại đây
            return Json(new { success = true }); // trả về JSON nếu muốn
        }
        // GET: Admin/AdminUsers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .Include(u => u.Department)
                .Include(u => u.Role)
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

    }
}

hethongquanlyluutrufiles/Areas/Admin/Views/Search/All_ListFilesSharedSearchPartial.cshtml
@model List<File>
@if (Model != null)
{
    foreach (var item in Model)
    {
        <tr role="row" class="odd">
            <td> @item.FileId</td>
            <td>@item.FileName</td>
            <td>@item.TypeFile.TypeFileName</td>
            <td>@item.DateUploaded </td>
            <td class="text-right">
                <a class="btn btn-primary btn-tone m-r-5" asp-area="Admin" asp-controller="AdminPermissViewFileAll" asp-action="PermissViewFile" asp-route-fileid="@item.FileId">Chọn</a>

            </td>
        </tr>
    }
}

hethongquanlyluutrufiles/Areas/Admin/Views/Search/Group_ListFilesSharedSearchPartial.cshtml
@model List<File>
@if (Model != null)
{
 foreach (var item in Model)
{
        <tr role="row" class="odd">
         <td> @item.FileId</td>
        <td>@item.FileName</td>
         <td>@item.TypeFile.TypeFileName</td>
        <td>@item.DateUploaded </td>
       <td class="text-right">
                <a class="btn btn-primary btn-tone m-r-5" asp-area="Admin" asp-controller="AdminPermissViewFileGroup" asp-action="PermissViewFile" asp-route-fileid="@item.FileId">Chọn</a>
        </td>
  </tr>
  }
}

hethongquanlyluutrufiles/Areas/Admin/Views/Search/ListFilesSearchPartial.cshtml
@model List<File>

@if (Model != null)
{
    foreach (var item in Model)
    {
        <tr>
            <th scope="row">@item.FileId</th>
            <td>@item.FileName</td>
            <td>@item.TypeFile.TypeFileName</td>
            <td>@item.DateUploaded</td>
            <td>
                <a class="btn btn-primary btn-tone m-r-5" asp-area="Admin" asp-controller="AdminFiles" asp-action="Edit" asp-route-id="@item.FileId">Edit</a>
                <a class="btn btn-secondary btn-tone m-r-5" asp-area="Admin" asp-controller="AdminFiles" asp-action="Details" asp-route-id="@item.FileId">Details</a>
                <a class="btn btn-success btn-tone m-r-5" asp-area="Admin" asp-controller="AdminFiles" asp-action="Delete" asp-route-id="@item.FileId">Delete</a>
            </td>
        </tr>
    }
}

hethongquanlyluutrufiles/Areas/Admin/Views/Search/ListUsersSearchPartial.cshtml
@model List<User>

@if (Model != null)
{
    foreach (var item in Model)
    {
        <tr>
            <th scope="row">@item.UserId</th>
            <td>@item.Username</td>
            <td>@item.Department.DepartmentName</td>
            <td>
                <div class="form-row d-flex justify-content-between p-t-5">
                    <div class="form-group d-flex align-items-center">
                        <div class="switch m-r-10">
                            <input type="checkbox" id="switch-1" checked="">
                            <label for="switch-1"></label>
                        </div>
                        <label>Able Shared</label>
                    </div>
                    <div>
                        <a class="btn btn-primary btn-tone m-r-5" asp-area="Admin" asp-controller="AdminUsers" asp-action="Details" asp-route-id="@item.UserId">Chi tiết</a>
                    </div>
                </div>
            </td>
        </tr>
    }
}

hethongquanlyluutrufiles/Areas/Admin/Views/Search/One_ListFilesSharedSearchPartial.cshtml
@model List<File>
@if (Model != null)
{
    foreach (var item in Model)
    {
        <tr role="row" class="odd">
            <td> @item.FileId</td>
            <td>@item.FileName</td>
            <td>@item.TypeFile.TypeFileName</td>
            <td>@item.DateUploaded </td>
            <td class="text-right">
                <a class="btn btn-primary btn-tone m-r-5" asp-area="Admin" asp-controller="AdminPermissViewFilePersonal" asp-action="PermissViewFile" asp-route-fileid="@item.FileId">Chọn</a>
            </td>
        </tr>
    }
}

hethongquanlyluutrufiles/Areas/Admin/Views/Search/One_ListUsersSharedSearchPartial.cshtml
@model List<User>
@if (Model != null)
{
    foreach (var item in Model)
    {
        <tr role="row" class="odd">
            <td>
                @item.UserId
            </td>
            <td>
                @item.Username
            </td>
            <td>@item.Sex</td>
            <td>@item.Role.TypeRole</td>
            <td>@item.Department.DepartmentName </td>
            <td class="text-right">
                <a class="btn btn-primary btn-tone m-r-5" asp-area="Admin" asp-controller="AdminPermissViewFilePersonal" asp-action="SelectFile" asp-route-userid="@item.UserId">Chọn</a>
            </td>
        </tr>
    }
}